FROM golang:1.11.1-alpine3.8

RUN apk add --no-cache git musl-dev gcc

COPY run-vendor.sh /usr/local/bin/run-vendor.sh
RUN chmod +x /usr/local/bin/run-vendor.sh

VOLUME [ "/src" ]
WORKDIR /src

ENTRYPOINT [ "run-vendor.sh" ]
