build_go: &build_go
  docker:
    - image: docker:18.06.1-ce-git
  steps:
    - checkout
    - setup_remote_docker
    - run:
        name: Build Image
        command: |
          docker image build -t $CIRCLE_PROJECT_USERNAME/gox-build:$CIRCLE_BRANCH-$GO_TAG -f Dockerfile-$GO_TAG .
    - deploy:
        name: Push to Docker Hub
        command: |
          if [ "$CIRCLE_BRANCH" == "$CIRCLE_TAG" ]; then
            docker login -u="${DOCKER_USERNAME}" -p="${DOCKER_PASSWORD}"
            docker push $CIRCLE_PROJECT_USERNAME/gox-build:$CIRCLE_BRANCH-$GO_TAG
          fi

version: 2
jobs:
  build_go1.11rc2-alpine3.8:
    environment:
      - GO_TAG: 1.11rc2-alpine3.8
    <<: *build_go


workflows:
  version: 2
  build-deploy:
    jobs:
      - build_go1.11rc2-alpine3.8
