build_go: &build_go
  docker:
    - image: docker:18.06.1-ce-git
  steps:
    - checkout
    - setup_remote_docker
    - run:
        name: Build Image
        command: |
          docker image build -t $CIRCLE_PROJECT_USERNAME/gox-build:develop -f Dockerfile-$GO_TAG .
    - deploy:
        name: Push to Docker Hub
        command: |
          if [ ! -z "$CIRCLE_TAG" ]; then
            docker login -u="${DOCKER_USERNAME}" -p="${DOCKER_PASSWORD}"
            OUTPUT_IMAGE=$CIRCLE_PROJECT_USERNAME/gox-build:$CIRCLE_TAG-$GO_TAG
            docker tag $CIRCLE_PROJECT_USERNAME/gox-build:develop $OUTPUT_IMAGE
            docker push $OUTPUT_IMAGE
          fi

version: 2
jobs:
  build_go1.11.0-alpine3.8:
    environment:
      - GO_TAG: 1.11.0-alpine3.8
    <<: *build_go


workflows:
  version: 2
  build-deploy:
    jobs:
      - build_go1.11.0-alpine3.8:
          filters:
            tags:
              only: /[0-9]+(\.[0-9]+)*/
